### ISSUE TITLE
[BC] GUI load machine error

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#111]
Hello,

if I load a machine once (e.g. IPMSM_A.json), go to '8 RotorLam' and try to load a machine again I get the follow error message.

![grafik](https://user-images.githubusercontent.com/43440731/85134900-7d1ca580-b23d-11ea-8170-14da90fd85df.png)

Best regrads,
Sebastian

**Comment by CedMrnl** [comment]
Hello Sebastian,

Sorry for this issue it must be linked to my recent changes in the GUI. 
I can't reproduce this issue. Have you got more messages in the terminal used to start the GUI? 
Is this bug only related to 8 RotorLam?

Best regards,
Cédric

**Comment by SebGue** [comment]
Hello Cédric,

I don't have any terminal messages. 
For me, the issue is reproducable on two different systems (both Win10 x64).
I figured out, it happens to all GUI pages every second time I try to load a machine.
Maybe someone else from your team can reproduce the issue. Otherwise I have to do some further research.

Best regards, Sebastian

**Comment by CedMrnl** [comment]
Hello Sebastian,

I managed to reproduce the bug. It should be corrected once Pierre accepts the PR.

Best regards,
Cédric
