### ISSUE TITLE
Option for no-load or full-load in simulations

### ISSUE THREAD

**Issue by Rushi2497** [Eomys/pyleecan#125]
Hello all,
Is there any option in pyleecan to simulate the defined motor for no-load and full-load conditions or at some %load condition?
Also, the electromagnetic torque output that we are currently getting from MagFEMM, is it the output at full-load conditions?

**Comment by BonneelP** [comment]
Hello,

For now the load is what you define. There is no "is_no_load" parameter (yet). You can either play with the current (by setting them to zero) or with the parameters is_mmfr and is_mmfs from MagFEMM. The torque output is then the torque for the current load. We will soon work on a better way to define the load of the machine (and in particular on how to loop on several load state).

Does it answer your question ? 
Best regards,
Pierre
