### ISSUE TITLE
GUI does not start due to config_dict reorganization

### ISSUE THREAD

**Issue by mxgnsr** [Eomys/pyleecan#126]
Hey guys,

Unfortunately the GUI doesn't work anymore due to the changes in commit 95166146.

Hopefully that can be fixed easily.

BR
Max

**Comment by BonneelP** [comment]
Hello, 

Thank you for noticing. It should be corrected now :)

Best regards,
Pierre

**Comment by mxgnsr** [comment]
Hello Pierre,

There is still a minor mistake in Functions/init_environment.py line 95-96 it should be "Dara" instead of "Plot"

BR
Max

**Comment by BonneelP** [comment]
Hello Max,

We have moved the pyleecan_color.json file into Data/Plot folder. In init_environment/init_user_dir (line 59) we now copy this folder into join(USER_DIR, "Plot"). The idea is that we copy some main files into APPDATA and then we don't use the join(MAIN_DIR, "Data") folder anymore. So I think lines 95 and 96 are Ok.

Best regards,
Pierre

**Comment by BonneelP** [comment]
Hello Max,

I changed the code anyway: if you were using an old version of the APPDATA folder then the Plot folder doesn't exist. Now we check that all the expected folder are present for the backward compatibility. You can also delete your previous version of the folder and it will be updated. 

Best regards,
Pierre

**Comment by mxgnsr** [comment]
Hello Pierre,

Yeah, the problem was on my side. Thanks for updating.

BR
Max
