### ISSUE TITLE
[CO] test data file size

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#147]
Hello Eomys,

I just recognized that there are 2 test data files that are nearly 90 MByte in total (which is larger than the project itself :-) ).
Would it affect unit testing if you'd reduce the size of that data?
The files are: 
Tests\Data\Plots\default_proj_Br.mat
Tests\Data\Plots\default_proj_Br_cfft2.mat

BR Sebastian

**Comment by CedMrnl** [comment]
Hello Sebastian, 

I agree that this size of data shouldn't be in the repository. 
As a quick fix I can put these files on pyleecan.com as we do for the tuto_Plots input data. 

Maybe we could use a better solutions like [zenodo](https://zenodo.org/) to host pyleecan data ?

Best regards,
Cédric
