### ISSUE TITLE
Bug with plot_contour

### ISSUE THREAD

**Issue by Superomeg4** [Eomys/pyleecan#153]
Hello everyone

I got some plot_contour issue. On my desktop the plot looks okay and on my laptop it is scattered (see below).
What data (of plot_contour) do I have to compare to distinguish if it's pyvista or pyleecan issue?
Data is MeshSolution class with solution if SolutionData class.

BTW: I think we should have file IO's that are more fault tolerant. I sometimes e.g. get an error regarding temp.vtk, since some of my files are on Dropbox synced folder and it's maybe a little slower than normal folders.

![grafik](https://user-images.githubusercontent.com/43440731/93309860-50f4ce80-f804-11ea-8782-117dafad95a0.png)
![grafik](https://user-images.githubusercontent.com/43440731/93310052-931e1000-f804-11ea-908e-32f0d8f8c769.png)

_Originally posted by @SebGue in https://github.com/Eomys/pyleecan/issues/48#issuecomment-693249783_

**Comment by SebGue** [comment]
I wanted to investigate further on this issue and noticed, that the patches flicker as I'am rotating the view. So it is clearly not a pyleecan issue, i.e. you (@Superomeg4 ) can close this one.
