### ISSUE TITLE
Results plots don't show off

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#154]
Hello everybody,

I tried to plot the results of a simulation (in IDLE) as it is done in the tutorials, e.g. with `myResults.plot_A_space('force.P', is_fft=True, r_max=40)`, but the plot don't show off. 
What am I doing wrong? Or is there some 'fig.show()' missing in the plot code?

Best regards, Sebastian

**Comment by CedMrnl** [comment]
Hello Sebastian, 

You're right, polt_A_space method does not return the figure and does not call `fig.show()`. I think that every plot should call automatically `fig.show()`.
As a quick fix in your script, I think that you can use `plt.show()` from *matplotlib.pyplot* or you can get the figure with `fig = plt.gcf()`.

Best regards,
Cédric
