### ISSUE TITLE
Make the plot commands more generic

### ISSUE THREAD

**Issue by helene-t** [Eomys/pyleecan#189]
Hi everyone,

We would like to make the plot commands more generic, with the possibility to slice over new axes (e.g. phases, z, radius), and remove the notion of "time" and "space" which is not always present in the data we want to plot. The titles would also become more precise.

Therefore, we suggest to rename the former `plot_A_2D`, `plot_A_3D` and `plot_A_4D` (which simply format the figure, given lists of ndarrays, titles, etc) as: `plot_2D`, `plot_3D` and `plot_4D`. No other modification should be necessary in these plot commands.

Then, `plot_A_space`, `plot_A_time`, `plot_A_fft_time` and `plot_A_fft_space` would be merged into a single plot command: `plot_2D_Data` with a syntax used in `SciDataTool`. For example:

`out.plot_2D_Data("mag.Br", "angle{°}")` or more advanced parameters such as:
`out.plot_2D_Data("mag.Br", "time", "angle[-1]", "phase[0,1,2]", "freqs=[0,5000]{elec_order}", unit="mT", is_norm=False)`

This syntax is heavier, but more generic, and avoids duplicating code.

Finally, `plot_A_surf`, `plot_A_fft2` and `plot_A_cfft2` would be merged into plot_3D_Data:

`out.plot_3D_Data("mag.B", "time", "space")` for a surface plot,
`out.plot_3D_Data("mag.B", "freqs", "wavenumber")` for a stem fft2 plot,
`out.plot_3D_Data("mag.B", "freqs", "wavenumber", is_2D_view=True)` for a 2D fft2 plot (former `plot_A_fft2`)

(One could similarly add intervals to plot_3D_Data: `"freqs=[0,5000]"`)

What do you think?

**Comment by BonneelP** [comment]
Done in release 1.0.2
