### ISSUE TITLE
[GUI] Error when try to run "run.GUI.py"

### ISSUE THREAD

**Issue by IvanMikulic1997** [Eomys/pyleecan#308]
Hello all,

I recently installed Pyleecan and I am having trouble with running the "run.GUI.py" script.

When I run it I got the following errors:

_Traceback (most recent call last):
  File "C:/Users/Ivan Mikulić/AppData/Local/Programs/Python/Python38/Lib/site-packages/pyleecan/run_GUI.py", line 6, in <module>
    from PySide2.QtCore import QTranslator
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyleecan\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyleecan\PySide2\__init__.py", line 55, in _setupQtDirectories
    os.add_dll_directory(dir)
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Ivan Mikulić\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\pyleecan\\libpyside'_

I would really appreciate your help on this because I don't know where is the issue.

**Comment by SebGue** [comment]
Hello Ivan,
it seems to be some issue with PySide. Are you able to import PySide manually?
Best regards, Sebastian

**Comment by IvanMikulic1997** [comment]
Hello Sebastian,

How do you mean "import PySide manually"? 

KR, Ivan

**Comment by SebGue** [comment]
Just open a python console and do 'from PySide2.QtCore import QTranslator'.
Or you create a python script with this import and run it, e.g. with idle.

**Comment by IvanMikulic1997** [comment]
Ok, I got it.
I put these two lines of code

_from PySide2.QtCore import QTranslator
translator = QTranslator()_

And I got the following error:

_Traceback (most recent call last):
  File "C:/Users/Ivan Mikulić/AppData/Local/Programs/Python/Python38/Lib/site-packages/pyleecan/proba.py", line 1, in <module>
    from PySide2.QtCore import QTranslator
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyleecan\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyleecan\PySide2\__init__.py", line 55, in _setupQtDirectories
    os.add_dll_directory(dir)
  File "C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Ivan Mikulić\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\pyleecan\\libpyside'

Process finished with exit code 1_

**Comment by SebGue** [comment]
What is your output if you move your script to another dir other than pyleecan, e.g. to C:\test

**Comment by SebGue** [comment]
Could you also run the following code

```
import sys >>> sys.path
```

**Comment by SebGue** [comment]
... you should also make sure that python is in your enviroment variable 'path', i.e. 'C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\' and 'C:\Users\Ivan Mikulić\AppData\Local\Programs\Python\Python38\Scripts\' in your case.

**Comment by SebGue** [comment]
![grafik](https://user-images.githubusercontent.com/43440731/106355271-214bec00-62f7-11eb-9add-2e234c16c5cf.png)

**Comment by IvanMikulic1997** [comment]
I checked the Path and everything is there as on the picture that you sent.

**Comment by IvanMikulic1997** [comment]
![image](https://user-images.githubusercontent.com/78252249/106356208-282a2d00-62fe-11eb-8050-54c0d9c17878.png)

**Comment by IvanMikulic1997** [comment]
I have run this code in the C\test and it seems that it worked

**Comment by IvanMikulic1997** [comment]
But now I don't get it why it don't work in the previous case?

**Comment by SebGue** [comment]
I don't get it eigther. But if your script is working in C/test you could try to also run pyleecan there, i.e.
```
from pyleecan import run_GUI

run_GUI()
```
Probably it is not possible to run a package from within its installation dir.
But I can not rreproduce this since I have not installed pyleecan with pip.

**Comment by IvanMikulic1997** [comment]
Thanks for the help. I successfully opened the GUI.
