### ISSUE TITLE
Rotor Initial Position

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#33]
At the moment the initial electrical rotor angle related to the stator winding system for arbitrary pol/slot-cominations is not known.

It would be useful to either have a function that calculates the initial rotor angle, i.e. for example the angle between the d-axis and the alpha-axis, or to modifiy the FEMM model creation in a way that the d-axis match the alpha-axis (in case `angle_rotor_initial=0`).

**Comment by BonneelP** [comment]
Solved in Pull request #34
