### ISSUE TITLE
Winding Generator

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#37]
Hello,

the winding distribution calculated by the pyleecan winding generator of a 1/2 slots per poles per phases winding has a clockwise direction, while other windings are anti-clockwise (e.g. 1 and 2 slots per poles per phases).
This should be corrected for consistency. 

Further if a tooth winding is reversed the tangential position of the coil sides will be wrong. Although that seems to have minor influence on simulation results, it should also be fixed.

Best regards,
Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,

While I'm cleaning the issues, I found this one. Sorry for the "rather long" wait for answer ^^'

We now have a better definition of rot_dir and unit_mmf so defining a unit test on this one should be more convenient. But next week we think about reorganizing the winding objects by introducing the star of slot method. I will soon open a issue to discuss about what would be the best architecture for winding. For now I close this issue, but I will link it in the next one.

Best regards,
Pierre
