### ISSUE TITLE
PWM voltage generator

### ISSUE THREAD

**Issue by Sijie-NI** [Eomys/pyleecan#375]
I am working for a PWM voltage generator at Pyleecan. This generator can produce 9 different PWM strategies with several variables. The output voltage can power machine models to observe and research the impact of harmonics from PWM signals on e-NVH.  

PWM generator can provide the following PWM strategies:
GDPWM
DPWMMIN
DPWMMAX
DPWM0
DPWM1
DPWM2
DPWM3
SVPWM
SPWM 

Several variables are available for SPWM:
Variable fundamental frequency
Variable switching frequency
Three different fixed switching frequency modes

![image](https://user-images.githubusercontent.com/64203774/116259189-e0d50080-a775-11eb-86f1-1adfa1f93a46.png)

**Comment by Sijie-NI** [comment]
The first version code has been updated in the EEC branch

**Comment by BonneelP** [comment]
Done in #377
