### ISSUE TITLE
Can't install pyleecan using pip install

### ISSUE THREAD

**Issue by azdinfaouzi** [Eomys/pyleecan#400]
I tried installing pyleecan using the command :
pip install pyleecan 
it gives me an error of something concerning iniconfig, i solved that probleme by installing the module through github install:
first you clone the repository:
git clone https://github.com/Eomys/pyleecan.git
then go to the location and run setup.py : 
sudo python setup.py install

**Comment by thalesmaoa** [comment]
```pip install git+https://github.com/Eomys/pyleecan.git```

**Comment by BonneelP** [comment]
Hello,

I managed to install pyleecan 1.3.7 (released last week) with pip and run the GUI. Do you still have some issue with pip or can we close this issue ? 

Best regards,
Pierre

**Comment by thalesmaoa** [comment]
Using an workaround for Linux. You can close.

**Comment by BonneelP** [comment]
Thanks you for your return
