### ISSUE TITLE
New random switching frequency strategies in PWM Voltage Generator (Random, Symmetrical random, Random Amplitude Modulation)

### ISSUE THREAD

**Issue by Sijie-NI** [Eomys/pyleecan#410]
Hello, 

I have created two new random switching frequency strategies in PWM Voltage Generator (Random and symmetrical random)

Random switching frequency (the frequency changes every 1/2 carrier period)
![test_ImportGenPWM_0_2_0_SPWM](https://user-images.githubusercontent.com/64203774/127156408-fe9f27d3-0f26-482c-bfee-d35e41410d9e.png)

Symmetrical switching frequency (the frequency changes every carrier period)
![test_ImportGenPWM_0_3_0_SPWM](https://user-images.githubusercontent.com/64203774/127157239-5586e986-b271-4e01-9279-9b56bf2bda0c.png)

Random Amplitude Modulation
![test_ImportGenPWM_0_4_0_SPWM](https://user-images.githubusercontent.com/64203774/127343893-96f67136-fa39-4897-9930-037fa039445c.png)

**Comment by EmileDvs** [comment]
Issue solved in PR #464
