### ISSUE TITLE
Working of jupyter notebook in vs code

### ISSUE THREAD

**Issue by Ksp-3086** [Eomys/pyleecan#427]
![vs code not drawing](https://user-images.githubusercontent.com/84498303/132084789-d7e4b64c-25b7-4471-a792-a2e4913441fa.png)
The code seems to run fine in vs code but it doesn't plot the machine as seen in the figure in tutorials. If I run the same code by copy pasting in python terminal, it plots the machine so why not here

**Comment by mxgnsr** [comment]
Hi, 

running it with the "%matplotlib notebook" statement did not work for me either. 
Can yout try "%matplotlib inline"?

BR
Max

**Comment by Ksp-3086** [comment]
Yeah thanks it did work although it gave a warning sort of "UserWarning: Matplotlib is currently using module://matplotlib_inline.backend_inline, which is a non-GUI backend, so cannot show the figure.
  fig.show()".
Can you tell me why this worked and why is this warning be shown? I can't see " fig.show()" in the code.

**Comment by mxgnsr** [comment]
According to this [Issue](https://github.com/microsoft/vscode-jupyter/issues/4056), vscode does currently not support the notebook-mode for matplotlib. Inline-mode seems to work, although I personally don't get that warning.
The `fig.show()` statement is part of the `machine.plot()` function.

**Comment by Ksp-3086** [comment]
ok thanks for the help
