### ISSUE TITLE
Visualization of magnetization direction and winding sign

### ISSUE THREAD

**Issue by Sijie-NI** [Eomys/pyleecan#443]
Hello, 

When I model an IPMSM with a spoke rotor, I find Pyleecan can not show the magnetization direction of magnets and winding sign in slots. Could we add the new features to visualize them in "machine plot". Because these signs are very important to understand the machine operation with applied current vectors. thanks a lot.  If possible, the rotation direction is also important. 
![image](https://user-images.githubusercontent.com/64203774/134863563-2911da09-cf95-4018-8718-f9f586557dbe.png)

Best regards, 

Sijie

**Comment by BonneelP** [comment]
Hello,

Good idea, here it is:
![image](https://user-images.githubusercontent.com/20533034/135521139-2d93eb81-e29c-4a9c-9ebf-b6c85bf6ca79.png)
This is the new default for plot machine. 
![image](https://user-images.githubusercontent.com/20533034/135521896-9e6e1483-e0f2-4427-b2ce-04e7642f81a1.png)

It is different from your drawing but it matches FEMM : 
![image](https://user-images.githubusercontent.com/20533034/135521544-ba7c93db-c271-429a-b55a-6ac2341774d9.png)

As a reminder we currently have:
![image](https://user-images.githubusercontent.com/20533034/135522081-472e27e8-7c9a-4969-9e0a-46741b1103f8.png)
Is it correct ? 

I have not added the rotation direction, I don't know a clean way to show that (adding an arrow would look strange I think). Maybe in a latter PR

Best regards,
Pierre
Ps: I also corrected an error regarding the periodicity of the machine
