### ISSUE TITLE
Look up table object to get electric circuits parameters for current operating point

### ISSUE THREAD

**Issue by EmileDvs** [Eomys/pyleecan#466]
Hello all,

The idea is to implement a new object look up table (LUT) that can store some eletrical parameters (such as phase resistance, magnetizing inductances, flux linkage etc.) at specific operating points and then be reload to calculate parameters for other operating points. The electrical parameters are then used to solve the electric equivalent circuit for the input operating point, defined by current/voltage/electrical frequency and temperatures of the different machine components (stator/rotor cores, magnets, windings etc.)

A new abstract class LUT have been implemented in PR #464 which contains stator resistance and reference temperatures at which parameters are pre calculated that are common to PMSM and SCIM. This LUT class is not usable in itself because the rest of the parameters depend on machine type. 

Therefore LUT class has two children with respect to the new operating points objects (cf issue #465 ):

- For PMSM, child class LUTdq contains Phi_wind at stator side for a grid Id/Iq (including Id=Iq=0) and interpolate within the grid to get Phid/Phiq and Ld/Lq. It also contains magnet flux linkage and other parameters such as magnet temperature to enable for temperature effect afterwards. LUTdq is for example used to calculate MTPA ( cf issue #467 ) or current harmonics due to PWM (cf issue #372), in validation case test_EEC_ELUT_PMSM.py.

- For SCIM, child class LUTslip contains Phi_wind at stator side for several level of stator currents at slip=0 to calculate magnetizing inductance function of saturation. The magnetizing inductance function of current can be only enforced for the moment, however it could be also calculated with MagFEMM such as it was done in EEC_SCIM (cf issue https://github.com/Eomys/pyleecan/issues/165). The method solve() of EEC_SCIM has been improved to include non-linearity of magnetizing inductance. The validation case for LUTslip is EEC_ELUT_SCIM.py and is still in progress.

Best regards,
Emile

**Comment by SebGue** [comment]
Hello @EmileDvs 

as you may know I would like to merge my LUT. If it is compliant, we will see :-)
Now the main differences are the following.

- Your LUT is not reproducable in the sence that (at least some of the) simulation paramters and the machine are unknown. My 'MagLUT' in contrast, is an inherited XOutput on an inherited var. Simu. (I still have to collect my code and send it to you as soon as possible.)

- I made my MagLUT in a way that I can use it for any compatible machine, i.e. machines with only another length and/or winding setup. So the LUT can easily be reused.

As said, I will prepare some code and send it. You only have to tell me if you are okay with the overhead in object size for reproducablility before we try to merge it.

BR S

**Comment by EmileDvs** [comment]
Hello @SebGue,

We already had the issue of missing some of the original simulation when handling LUT, so it is a good idea to have inherited LUT from XOutput actually. 

I think we can simply merge our approaches if we inherit LUT from XOutput and get the quantities (e.g. Phi_wind) through getters.

We don't have problems of overhead in object size since we mainly use .h5 save format, so data is already compressed.

As asked in PR #464, is it ok for you if we handle this in a new branch of EOMYS-Public and we merge the current PR ?

Best regards,
Emile
