### ISSUE TITLE
[NF] Implementation of bayesian optimisation

### ISSUE THREAD

**Issue by nnassar98** [Eomys/pyleecan#475]
The NSGA-II algorithm is already implemented in `tuto_Optimization.ipynb` and will serve as a reference for further developments in the implementation of a **Bayesian optimization algorithm** for the design of electric motors. The implementation will be based on existing python libraries as:
- https://smt.readthedocs.io/en/latest/_src_docs/applications/ego.html
- https://gpflowopt.readthedocs.io/en/latest/notebooks/constrained_bo.html
- https://secondmind-labs.github.io/trieste/notebooks/inequality_constraints.html

In particular, some parameters in the design of the machines are discrete (example: the number of notches in the stator). The first SMT library allows to perform optimizations with mixed variables (continuous AND discrete) but without constraints (for example, "optimize for a number of notches between 10 and 24"). In the current state of knowledge, it is envisaged to use one of the two other packages in a complementary way in order to remove this obstacle.

Thus, the 3 main objectives are:
1. To realize a Bayesian optimization algorithm without constraints on continuous variables. 
2. Add the constraints to the previous algorithm. 
3. Add discrete variables.

**Comment by BonneelP** [comment]
The corresponding PR was #514 and is merged
