### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#520]
Hello, 

I guess with the latest updates in SciDataTool we need some update of requirements.txt regarding matplotlib.
With matplotlib 3.3.4 I got some error message. 

BR S

**Comment by BonneelP** [comment]
Hello Sebastian,

I just saw that we didn't answer this issue, sorry for that :/ I guess that the issue is solved now with the latest version of SciDataTool or do we still need to update the requirements ? 

Best regards,
Pierre

**Comment by SebGue** [comment]
Hello Pierre,

I can't recall what the actual issue was. I just downgraded to matplotlib 3.3.2 and every thing seems to work at the first glance.
So I will close the issue for now.

Best regards, Sebastian
