### ISSUE TITLE
Not able to install pyleecan on windows 10 

### ISSUE THREAD

**Issue by harbnh** [Eomys/pyleecan#522]
Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Collecting deap>=1.3.1
  Using cached deap-1.3.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in deap setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

********************************************************************************************************System details****************8
>pip --version
pip 22.0.4

**Comment by BonneelP** [comment]
Hello,

Sorry for the late answer. Someone else just had the same issue, so I just released a new version of pyleecan that should help.
More information at #542.
I'm closing this issue as it's now a duplicate, we can carry on the discussion in #542

Best regards,
Pierre
