### ISSUE TITLE
plot_schematics partially ignores fig and ax parameters, and produces an extra figure.

### ISSUE THREAD

**Issue by mjfwest** [Eomys/pyleecan#531]
As in the title.  The minimum example is:
```python
figs = list(map(plt.figure, plt.get_fignums()))
print('Number of figures {0}'.format(len(figs)))

# create two side by side subplots on one figure
fig22, (ax1, ax2) = plt.subplots(1, 2)
# plot the slot shape on the left hand subplot (first figure below)
stator.slot.plot(fig=fig22, ax=ax1)
# try and plot the schematics on the right hand axis
stator.slot.plot_schematics(fig=fig22, ax=ax2, is_default=False,
                            is_show_fig=False,
                            is_add_point_label=True)
#(2nd Figure) Two things have gone wrong already, 1. plot_schematics has taken fig and ax
# as parameters, but it seems to ignore the ax parameter when plotting the slot
# shape but uses the correct ax when plotting the labels.  2. it has created
# another figure that I didn't ask for with the stator and winding plotted.

figs = list(map(plt.figure, plt.get_fignums()))
print('Number of figures {0}, and fig22 is one of them {1}'.format(
    len(figs), fig22 in figs))
fig22.savefig('error_plot_part_2.png')
```
The first figure is the result of plotting the slot on the left axis and is correct.

![error_plot_part_1](https://user-images.githubusercontent.com/1198074/164180189-1b3c449f-6bbe-4f31-839e-af5606e57d62.png)
calling plot schematics on the right hand axis produces this error, and the output `
Number of figures 2, and fig22 is one of them True`
![error_plot_part_2](https://user-images.githubusercontent.com/1198074/164180205-29a11d37-2750-4b49-821b-6b91b17ec411.png)

The culprit for the first part is probably this section of `plot_schematics.py:
```python
        # Getting the main plot
        if self.parent is None:
            raise ParentMissingError("Error: The slot is not inside a Lamination")
        lam = self.parent
        lam.plot(alpha=pi / self.Zs, is_show_fig=False)  # center slot on Ox axis
        if fig is None or ax is None:
            fig = plt.gcf()
            ax = plt.gca()
```
Changing it to `if fig is None and ax is None:` will fix this problem, but will need checks for `fig is None and ax is not None:` etc.

I've not yet found where the 2nd figure is being produced from.

**Comment by BonneelP** [comment]
Hello,

Which slot are you using ? I haven't checked all the slots but it seems that most of them share the following arguments:
![image](https://user-images.githubusercontent.com/20533034/164751230-e90e06e4-f4dd-4530-83e3-380a01843cb4.png)
In most of them, we call a plot of the lamination then get the corresponding fig and ax to add the schematics information.
![image](https://user-images.githubusercontent.com/20533034/164751445-87f5ec0a-7a1f-4561-9ef9-e8a2b5ffc4dc.png)
Maybe we could do better by calling the init_fig function in the plot_schematics method and passing fig, ax to lam.plot().

Do you need the fig, ax argument to add the schematics on an existing plot ?

Best regards,
Pierre

**Comment by mjfwest** [comment]
This is using `SlotW23`.  In general yes, I want to control where the plot ends up, and what it looks like  The really cool bit that pyleecan is doing for me is generating all the patches, annotations, etc, and adding them to an axis; every assumption it makes after adds little benefit, and often needs correcting.  

I think your suggestion sounds like a solution.  Does the `init_fig` method exist, or does it need writing?

**Comment by BonneelP** [comment]
cf final answer to #527
