### ISSUE TITLE
Can we export full stator+Rotor+ frame as .fem machine after we model it in pyleecan 

### ISSUE THREAD

**Issue by crowdnidhi-design** [Eomys/pyleecan#587]

**Comment by BonneelP** [comment]
Hello,
If you are using the GUI the .fem file is available in the result folder that you have selected after the computation (you can also use the draw in FEMM button). 
In scripting mode, you can enforce the output folder path and if you are looking for the full machine, you can remove the periodicity with something like simu.mag.is_periodicity_a=False.
Best regards,
Pierre

**Comment by crowdnidhi-design** [comment]
thanks a bunch I will try it.
