### ISSUE TITLE
ImportError: cannot import name 'FEMMHandler'

### ISSUE THREAD

**Issue by crowdnidhi-design** [Eomys/pyleecan#592]
ImportError                               Traceback (most recent call last)
Cell In[1], line 22
     19 example1.plot()
     21 # Check FEMM installation
---> 22 from pyleecan.Classes._FEMMHandler import FEMMHandler
     24 femm = FEMMHandler()
     25 femm.openfemm(0)

ImportError: cannot import name 'FEMMHandler' from 'pyleecan.Classes._FEMMHandler' (c:\users\haris\downloads\pyleecan-1.4.2.tar\pyleecan-1.4.2\pyleecan-1.4.2\pyleecan\Classes\_FEMMHandler.py)

**Comment by crowdnidhi-design** [comment]
how to solve the above issue pls

**Comment by BonneelP** [comment]
Hello, 

Do you still have this error ? I think it may be just a typo "FEMMHandler" instead of "_FEMMHandler"

Best regards,
Pierre

**Comment by crowdnidhi-design** [comment]
No. I have resolved it.
