### ISSUE TITLE
Trying to understand InputVoltage class

### ISSUE THREAD

**Issue by Omar-P1** [Eomys/pyleecan#613]
Hello,
I recently started working with Pyleecan, and I'm trying to model an IPMSM machine. I wanted to understand how to make the best use of the InputVoltage class, possibly through some code examples.
I was interested in understanding whether I need to specify Ld, Lq every time, or once the machine and the equivalent circuit have been created, can they be computed automatically.
Thank you.

**Comment by BonneelP** [comment]
Hello,

Thank you for your interest in pyleecan. Unfortunately there is no tutorial detailing InputVoltage (only electrical tutorial is here: https://pyleecan.org/tuto_Elec.html). 

Regarding InputVoltage usage exemples, what you can do is get pyleecan code (method 3 from https://pyleecan.org/get.pyleecan.html) and search the class in all pyleecan and in particular in the Tests folder. Here is all the tests that you can take inspiration from: 
![image](https://user-images.githubusercontent.com/20533034/227590923-6f74d90b-306a-41a7-9bc6-cb17f8f7e1fe.png)
Note that you can also find these files directly on Github: https://github.com/Eomys/pyleecan/blob/master/Tests/Validation/Electrical/test_EEC_ELUT_SCIM.py

Hope it helps,
Best regards,
Pierre
