### ISSUE TITLE
Installation issue with Python 3.11

### ISSUE THREAD

**Issue by lusu91** [Eomys/pyleecan#615]
Hello everyone,

I would like to report that installing pyleecan package via pip command on a virtual environment running Python 3.11 gives me an error.
In particular, he does not like the dependence on a package that is not present in PyPI: swat-em@ git+.

I copy and paste the error message for completeness:
<details><summary>Details</summary>
<p>
Collecting pyleecan<br>
  Using cached pyleecan-1.4.1.tar.gz (11.9 MB)<br>
  Preparing metadata (setup.py) ... done<br>
  Using cached pyleecan-1.4.0.tar.gz (11.5 MB)<br>
  Preparing metadata (setup.py) ... done<br>
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.<br>
pyleecan depends on swat-em@ git+https://gitlab.com/CedMrnl/swat-em.git<br>
</p>
</details> 

I also tried to install swat-em.git separately, as suggested in another issue, without success ([link to the post](https://github.com/Eomys/pyleecan/issues/580#issuecomment-1357289149)).

**Comment by BonneelP** [comment]
Hello,

Thank you for your interest in pyleecan. Sadly it's a known issue (cf end of #120): pyleecan is not yet compatible with Python 3.11
For next release we will indicate in pip that pyleecan is not compatible with this version of python and when we will have some time we will investigate moving to 3.11 

Best regards,
Pierre
