### ISSUE TITLE
[BC] Material Library

### ISSUE THREAD

**Issue by SebGue** [Eomys/pyleecan#62]
Hello to everybody,

I have been testing the current implementation of the MatLib-Editor within the pyleecan GUI and recognized some short comings. For instance, if a material is edited, the changes are not propagated thoughout the whole machine.
Therefore I would like to discuss the behavior that everybody would expect from the Material Library Editor.
Here are some thoughts and questions from my side.
- changes to material library should propagate to all machine parts if they use the respective material, i.e. material object references should not been broken
- Material Library should show the origin of the currently selected material (MatLib or Path)
- it should not been allowed to have duplicate material names
- if a loaded machine contains "new" material, the user should be asked to add this material to the library, to keep it as is or to replace it with a material from the library that has the same data, if it exists
- if there are materials with the same name (in the machine file and/or the library) the user should be asked to rename the material
- an alternative may also be to keep the machine files materials "outside" the library and only inside the material selection combobox with the possiblity to also edit that material (that may require some additional logic to handle all possible cases)

All of your contribution to this issue is greatly appreciated.

Best regrads,
Sebastian

**Comment by BonneelP** [comment]
Hello Sebastian,

Thank you for this interesting issue. The reason the Matlib is working that way is a legacy from MANATEE where the material are stored in separated files from the machine one. For MANATEE only the name of the Material is meaningful for the selection and everything is loaded at the beginning of the simulation. The MatLib only update the material file for later use.

I agree that we need to change that to have something more coherent with pyleecan. 

Note that we currently save the material within the machine object which can cause the following issue: I create a machine with Mat_A, save it, change some value of Mat_A latter, then come back to the old machine which still has the old value of Mat_A (but I may expect to have the new value). To avoid that when loading a machine we can overwrite the material with the current version of the material library. If we need to create such function when loading a machine we can call this function when updating the material library. That way the material in the MatLib are the reference.

The GUI breaks the material reference to enable the user to cancel its modification which can be interesting when you may change a material used in several machines. But it may be not necessary if we create a copy of the material and then call the init method of the current instance with the as_dict of the copy. 

Regarding the "origin" of the material I don't understand what you mean but we can display the path to the file.

I agree for the duplicated name

> if a loaded machine contains "new" material, the user should be asked to add this material to the library, to keep it as is or to replace it with a material from the library that has the same data, if it exists

I agree if we detect a new material by checking only its name. 

What do you think of the idea to use the MatLib as the reference for all material handled within the GUI ? 

Best regards,
Pierre
